// "The Illustrator Heist" (השוד של המאייר), V1 launch story.
// Source of truth for the design: docs/stories/illustrator-heist.md.
// Placeholders in {braces} are filled from the active skin.

export const illustratorHeist = {
  id: 'illustrator-heist',
  version: 1,
  title: 'השוד של המאייר',
  tagline: 'קלף של 20 מיליון. 94 שניות של חושך. שני גנבים.',
  minPlayers: 6,
  maxPlayers: 9,
  durationMin: 150,
  defaultSkin: 'sellable',
  skins: {
    sellable: {
      tcg: 'Wildlore TCG',
      card: 'Noctyra Illustrator',
      creature: 'Noctyra',
      grader: 'SlabCert',
      photoApp: 'Pixelgram',
      streamApp: 'Streamly',
      chatApp: 'Huddle',
      kingHandle: 'noctyra_king',
    },
    private: {
      tcg: 'Pokémon TCG',
      card: 'Pikachu Illustrator',
      creature: 'Pikachu',
      grader: 'PSA',
      photoApp: 'Instagram',
      streamApp: 'Twitch',
      chatApp: 'Discord',
      kingHandle: 'pikachu_king',
    },
  },

  premise:
    'תל אביב, 21:00. ערב תצוגה פרטי בבית המכירות Hammer & Holo. מחר יימכר הקלף המפורסם בארץ: {card}, בדירוג {grader} GEM 10. ' +
    'הוא ניתן כפרס בתחרות איור ב־1998, ורק כ־40 עותקים הודפסו. הערכה: 18–22 מיליון ₪. ' +
    'ב־21:43 החשמל נופל ל־94 שניות. כשהאורות חוזרים, הקלף עדיין בוויטרינה. ' +
    'בבדיקת UV מתברר: הוא מזויף.',

  characters: [
    {
      id: 'eitan',
      name: 'איתן ברק',
      role: 'בעל הקלף',
      core: true,
      handle: '{kingHandle}',
      bio: 'אספן. שעונים, קלפים מדורגים, ומעט מדי שינה.',
      publicIntro: 'הבעלים של {card}. מחר בערב הוא אמור להיות עשיר מאוד.',
      secret:
        'אתה שקוע בחובות קריפטו של כ־6 מיליון ₪. לפני שלושה שבועות העלית את הביטוח מ־8 ל־20 מיליון. ' +
        'ביקשת מנועה להכין "רפליקה לתצוגה", קיבלת משירה גישת מנהל לאפליקציית האבטחה, ' +
        'וב־21:43 הפעלת "מצב האפלה". בחושך החלפת את הקלף ברפליקה ושמת את האמיתי בכיס הז׳קט שלך בחדר המעילים. ' +
        'כשבדקת את הז׳קט אחרי זה, הקלף האמיתי כבר לא היה שם. מישהו גנב ממך את הגניבה.',
      goal: 'להסיט את החשד לרותם, ולגלות מי לקח את הקלף מהז׳קט שלך. בלי להודות בכלום.',
      costume: 'ז׳קט כהה ושעון זהב גדול על היד. השעון חשוב.',
      fits: ['schemer', 'talker'],
      guilty: true,
    },
    {
      id: 'noa',
      name: 'נועה לוי',
      role: 'מומחית דירוג',
      core: true,
      handle: 'noa.grades',
      bio: 'Slab Queen. מדרגת קלפים, לא אנשים.',
      publicIntro: 'המומחית שאישרה את הדירוג. היא זו שתעשה את בדיקת ה־UV.',
      secret:
        'איתן הזמין ממך "רפליקה לתצוגה" של הקלף, כולל תווית {grader} מודפסת. בערב שלפני העלית סטורי של שולחן העבודה ומחקת אותו מהר. ' +
        'את לא יודעת שהוא החליף את הקלפים, אבל את מתחילה לחשוד.',
      goal: 'לוודא שאף אחד לא משחזר את הסטורי שלך מ־20:10, ולהישאר מעל כל חשד.',
      costume: 'משקפי קריאה על הראש, כפפות כותנה לבנות בכיס.',
      fits: ['detective', 'chill'],
      guilty: false,
    },
    {
      id: 'yoni',
      name: 'יוני ברק',
      role: 'אחיו של איתן, סטרימר',
      core: true,
      handle: 'YoniOpensPacks',
      bio: 'פותח חבילות בלייב. 12 אלף עוקבים ואמא.',
      publicIntro: 'שידר את כל הערב בלייב ב־{streamApp}. המצלמה שלו ראתה הכל.',
      secret: 'הסטרים שלך תפס את רגע ההחלפה, ואתה לא שמת לב. אם תצפה בהקלטה, תזהה את השעון של אחיך.',
      goal: 'להגיע ל־100 "צופים": כל שחקן שעושה משהו מול המצלמה שלך מוסיף 30 צופים.',
      costume: 'קפוצ׳ון, אוזניות על הצוואר, טלפון תמיד ביד.',
      fits: ['talker', 'chill'],
      guilty: false,
    },
    {
      id: 'gal',
      name: 'גל פרץ',
      role: 'עובד בחנות הקלפים (17)',
      core: true,
      handle: 'gal.flips',
      bio: 'קונה בזול, מוכר ביוקר. בדרך כלל.',
      publicIntro: 'העובד הצעיר של החנות. מכיר כל קלף בחדר.',
      secret:
        'אתה חייב כסף למלווה בשוק האפור מ־{chatApp}. ראית על המסך של יוני את היד של איתן בוויטרינה. ' +
        'ב־21:51 נכנסת לחדר המעילים ולקחת את הקלף האמיתי מהז׳קט של איתן. הוא מוסתר עכשיו בבית.',
      goal: 'לא להיתפס. אם נתפסת, לנסות לעשות עסקה: הקלף תמורת שתיקה.',
      costume: 'חולצת החנות, תיק גב, ריח קל של ספריי ניקוי.',
      fits: ['schemer', 'chill'],
      guilty: true,
    },
    {
      id: 'maya',
      name: 'מאיה כהן',
      role: 'נציגת בית המכירות',
      core: true,
      handle: 'maya.hammerandholo',
      bio: 'Hammer & Holo · מכירות פומביות מאז 2011.',
      publicIntro: 'מארחת הערב. המכירה של מחר היא הגדולה בתולדות הבית.',
      secret: 'בית המכירות כמעט פושט רגל. בלי המכירה מחר, כולם מפוטרים, כולל את.',
      goal: 'לשכנע את כולם שהמכירה תתקיים ושהקלף האמיתי עוד בבניין.',
      costume: 'בלייזר, תג שם, פטיש מכירות קטן.',
      fits: ['talker', 'detective'],
      guilty: false,
    },
    {
      id: 'rotem',
      name: 'רותם שני',
      role: 'הגרושה של איתן',
      core: true,
      handle: 'rotem.after',
      bio: 'אחרי. ומאושרת. בערך.',
      publicIntro: 'הגיעה "רק להגיד שלום". כולם יודעים שזה לא נכון.',
      secret:
        'בהליך הגירושין את טוענת שחצי מהאוסף שלך, כולל הקלף. אם הוא יימכר מחר, תצטרכי להוכיח את זה מהר.',
      goal: 'למצוא הוכחה שאיתן מסתיר כסף, ולהציג אותה לכולם.',
      costume: 'שמלה שחורה, משקפי שמש גם בפנים.',
      fits: ['talker', 'schemer'],
      guilty: false,
    },
    {
      id: 'shira',
      name: 'שירה אברהמי',
      role: 'מתקינת מערכות אבטחה',
      core: false,
      handle: 'shira.secure',
      bio: 'מצלמות, חיישנים, ושקט נפשי.',
      publicIntro: 'התקינה את מערכת האבטחה של האולם.',
      secret: 'נתת לאיתן גישת מנהל לאפליקציית האבטחה "רק לערב אחד". יש לך את הלוג של המערכת.',
      goal: 'להגן על החברה שלך. להחליט מתי לחשוף את הלוג, ואם בכלל.',
      costume: 'מכנסי דגמ״ח, מחזיק מפתחות ענק.',
      fits: ['detective', 'chill'],
      guilty: false,
    },
    {
      id: 'kenji',
      name: 'קנג׳י מורי',
      role: 'אספן מיפן',
      core: false,
      handle: 'mori.collection',
      bio: 'אוסף של אבי, 1978–1999.',
      publicIntro: 'אספן ותיק שהגיע במיוחד מאוסקה.',
      secret: 'לדבריך, הקלף נלקח מהאוסף של אביך ב־1998. אין לך שום הוכחה.',
      goal: 'לספר את הסיפור של אביך, ולגייס לפחות שני תומכים.',
      costume: 'חליפה מחויטת, כפפות לבנות.',
      fits: ['chill', 'detective'],
      guilty: false,
    },
    {
      id: 'ido',
      name: 'עידו',
      role: 'מודרטור בסטרים של יוני',
      core: false,
      handle: 'ido.mod',
      bio: 'המוד הכי מהיר בצ׳אט.',
      publicIntro: 'החבר הכי טוב של יוני. מנהל לו את הצ׳אט.',
      secret: 'יש לך את קובץ הסטרים המלא, כולל מה שקרה בחדר המעילים.',
      goal: 'למכור את הקובץ למי שיציע הכי הרבה, בכסף משחק או בסוד.',
      costume: 'חולצת גיימינג, שרוך עם תג "MOD".',
      fits: ['schemer', 'talker'],
      guilty: false,
    },
  ],

  npcs: [
    {
      id: 'nili',
      name: 'פקד נילי דגן',
      title: 'יחידת חקירות',
      tone: 'יבשה, מצחיקה, עייפה. עונה קצר. לא מנחשת.',
      opening: 'ערב טוב. איפה היית ב־21:43?',
      knows: [
        'החשמל נפל ב־21:43 לתשעים וארבע שניות.',
        'בדיקת UV ב־22:10 הוכיחה שהקלף בוויטרינה מזויף.',
        'הוויטרינה לא נפרצה. מי שהחליף ידע איך לפתוח אותה.',
      ],
      dodges: ['לא מנחשת מי עשה את זה.'],
      underPressure: ['אם מזכירים את הסטרים: "הייתי בודקת מה קרה בחדר המעילים."'],
      fallback: [
        {
          keywords: ['סטרים', 'שידור', 'יוני', 'הקלטה', 'streamly'],
          reply: 'סטרים? הייתי בודקת מה קרה בחדר המעילים. בערך עשר דקות אחרי ההפסקה.',
        },
        {
          keywords: ['ויטרינה', 'נפרץ', 'מנעול', 'פתח'],
          reply: 'הוויטרינה לא נפרצה. מי שהחליף ידע איך לפתוח אותה. או שהיה לו מפתח.',
        },
        {
          keywords: ['חשמל', 'הפסקה', 'חושך', '21:43'],
          reply: '21:43. תשעים וארבע שניות. זה לא קצר, זה לא ארוך. זה בדיוק מספיק.',
        },
        {
          keywords: ['uv', 'מזויף', 'זיוף', 'בדיקה'],
          reply: 'הבדיקה ב־22:10 חד־משמעית. זה לא הקלף. השאלה היא מתי הוא הפסיק להיות הקלף.',
        },
        { keywords: ['מי', 'חשוד', 'אשם'], reply: 'אני לא מנחשת. אני אוספת. תביאו לי משהו.' },
      ],
      fallbackDefault: 'רשמתי. עוד משהו? אני לא צעירה.',
    },
    {
      id: 'avner',
      name: 'אבנר',
      title: 'מכולת עתיקות, יפו',
      tone: 'מדבר מהר, לחוץ, מתחמק. מתרכך אם מתעקשים.',
      opening: 'כן? מי זה? אני סוגר עוד מעט.',
      knows: ['הבוקר מישהו התקשר ושאל כמה שווה {card}, "באופן היפותטי".'],
      dodges: ['אומר שהוא "לא זוכר" את הקול.'],
      underPressure: ['"ילד. עם תיק גב. הריח כמו ספריי ניקוי של חנות."'],
      fallback: [
        {
          keywords: ['נער', 'ילד', 'צעיר', 'בחור', 'תיק', 'מי זה היה', 'איך נראה', 'תאר'],
          reply: 'טוב, טוב! ילד. צעיר. עם תיק גב. והריח שלו… כמו ספריי ניקוי של חנות. מרוצים?',
        },
        {
          keywords: ['שאל', 'התקשר', 'בוקר', 'מחיר', 'שווה'],
          reply: 'מישהו התקשר הבוקר ושאל כמה שווה {card}. "היפותטית". אמרתי לו שהיפותטית הוא ילך לכלא.',
        },
        { keywords: ['קנה', 'מכר', 'הביא'], reply: 'אף אחד לא הביא לי כלום! אני עסק כשר.' },
      ],
      fallbackDefault: 'לא יודע, לא זוכר, לא ראיתי. אני סוגר.',
    },
    {
      id: 'dafna',
      name: 'דפנה רוט',
      title: 'שמאית ביטוח',
      tone: 'מנומסת, קרה, מדויקת. לא מוסרת פרטים אישיים.',
      opening: 'דפנה רוט, מחלקת תביעות. יש לי כמה שאלות, ואני מניחה שגם לכם.',
      knows: ['הכיסוי הביטוחי על הקלף הועלה לפני שלושה שבועות.'],
      dodges: ['לא אומרת מי ביקש את השינוי.'],
      underPressure: ['"בעל הפוליסה ביקש את השינוי בעצמו."'],
      fallback: [
        {
          keywords: ['מי ביקש', 'מי העלה', 'בעל הפוליסה', 'איתן', 'ביקש'],
          reply: 'אם אתם מתעקשים: בעל הפוליסה ביקש את השינוי בעצמו. זה כל מה שאני יכולה לומר.',
        },
        {
          keywords: ['ביטוח', 'פוליסה', 'כיסוי', 'העלה', 'מיליון', 'סכום'],
          reply: 'הכיסוי על הפריט הועלה לפני שלושה שבועות. מ־8 ל־20 מיליון. תזמון… מעניין.',
        },
      ],
      fallbackDefault: 'אני לא מוסרת פרטים על מבוטחים. נסו לשאול שאלה אחרת.',
    },
  ],

  clues: [
    {
      id: 'fake_photo',
      title: 'צילום הקלף המזויף',
      kind: 'photo',
      summary: 'הקלף שבוויטרינה, מקרוב. על התווית: CERT #48213307.',
      body: 'צילום תקריב של ה־slab שבוויטרינה אחרי בדיקת ה־UV. הכנפיים לא זוהרות. על התווית: {grader} · GEM MT 10 · CERT #48213307.',
      visual: 'fake-slab',
      unlock: { type: 'manual' },
      audience: 'all',
      pointsTo: [],
      hint: 'לכל קלף מדורג יש מספר תעודה. אפשר לבדוק אותו בכלי {grader}.',
    },
    {
      id: 'uv_test',
      title: 'בדיקת UV',
      kind: 'physical',
      summary: 'שני קלפים מודפסים ופנס UV. רק אחד זוהר.',
      body: 'בערכה יש שני קלפים מודפסים ופנס UV. בקלף האמיתי יש דיו שזוהר בתאי הכנפיים. האירו על שניהם, ומצאו את ההבדל.',
      visual: 'uv-kit',
      unlock: { type: 'manual' },
      audience: 'all',
      pointsTo: [],
    },
    {
      id: 'cert_lookup',
      title: 'תוצאת בדיקת תעודה',
      kind: 'lookup',
      summary: 'התעודה #48213307 שייכת לקלף אחר לגמרי, שדורג ב־2019.',
      body: '{grader} #48213307 · 2019 WILDLORE KINTSU HOLO · GEM MT 10 · תאריך דירוג: 14.03.2019.\nמישהו הדפיס תווית אמיתית של קלף אחר, והדביק אותה על הזיוף.',
      visual: 'cert-result',
      unlock: { type: 'answer', tool: 'slabcert', accept: ['48213307'] },
      audience: 'all',
      pointsTo: ['noa'],
      hint: 'בצילום של הקלף המזויף יש מספר תעודה. נסו אותו בכלי {grader}.',
      hintFromMin: 42,
    },
    {
      id: 'stream_frame',
      title: 'פריים מהסטרים, 21:43:07',
      kind: 'photo',
      summary: 'יד עם שעון זהב גדול ליד הוויטרינה, באמצע ההאפלה.',
      body: 'פריים מההקלטה של YoniOpensPacks, בזמן 21:43:07. בחושך, באור של הוויטרינה, רואים יד עם שעון זהב גדול פותחת את הדלת.',
      visual: 'stream-frame',
      unlock: { type: 'manual' },
      audience: 'all',
      pointsTo: ['eitan'],
      hint: 'למי בחדר יש שעון זהב גדול?',
    },
    {
      id: 'coat_room_chat',
      title: 'הודעה בצ׳אט, 21:51',
      kind: 'chat',
      summary: '"יו מי זה בחדר המעילים??"',
      body: 'בצ׳אט של הסטרים, 21:51, המשתמש shadowmod כתב: "יו מי זה בחדר המעילים??". ברקע של המצלמה נראית דמות עם תיק גב.',
      visual: 'stream-chat',
      unlock: { type: 'after', clue: 'stream_frame', delayMin: 15 },
      audience: 'all',
      pointsTo: ['gal'],
      hint: 'שמונה דקות אחרי ההאפלה, מישהו היה בחדר המעילים. מי הגיע עם תיק גב?',
    },
    {
      id: 'noa_story',
      title: 'הסטורי שנמחק של @noa.grades',
      kind: 'photo',
      summary: 'שולחן העבודה של נועה ב־20:10: slab ריק, מדפסת תוויות, ותוויות עם אותו מספר תעודה.',
      body: 'סטורי ששוחזר, 20:10: שולחן עבודה עם slab ריק, מדפסת תוויות ודף של תוויות {grader} עם CERT #48213307. הכיתוב: "עבודת לילה 🤫 רפליקה לתצוגה בלבד".',
      visual: 'noa-story',
      unlock: { type: 'qr', code: 'NOA-2010' },
      audience: 'all',
      pointsTo: ['noa', 'eitan'],
      hint: 'סטוריז לא באמת נמחקים. חפשו מדבקת QR בבית.',
      hintFromMin: 60,
    },
    {
      id: 'security_log',
      title: 'לוג מערכת האבטחה',
      kind: 'log',
      summary: '21:43:02: "מצב האפלה" הופעל על ידי eitan.b.',
      body: 'SecureHall · לוג אירועים\n21:40:11  התחברות מנהל: eitan.b (הרשאה זמנית, אושרה ע״י shira.a)\n21:43:02  "מצב האפלה" הופעל: eitan.b\n21:44:36  "מצב האפלה" בוטל: eitan.b',
      visual: 'security-log',
      unlock: { type: 'manual' },
      audience: 'all',
      pointsTo: ['eitan'],
    },
    {
      id: 'security_log_private',
      title: 'הלוג שלך (רק את רואה)',
      kind: 'log',
      summary: 'הלוג מראה מי הפעיל את ההאפלה. את מחליטה מתי לחשוף.',
      body: 'SecureHall · לוג אירועים\n21:40:11  התחברות מנהל: eitan.b (הרשאה זמנית, אושרה ע״י shira.a)\n21:43:02  "מצב האפלה" הופעל: eitan.b',
      visual: 'security-log',
      unlock: { type: 'time', atMin: 70 },
      audience: ['shira'],
      pointsTo: ['eitan'],
    },
    {
      id: 'insurance_email',
      title: 'מייל מחברת הביטוח',
      kind: 'email',
      summary: 'הכיסוי על הקלף הועלה מ־8 ל־20 מיליון, לפני שלושה שבועות.',
      body: 'מאת: מחלקת פוליסות\nנושא: אישור שינוי כיסוי, פוליסה 7781-B\nבהמשך לבקשתך, סכום הכיסוי לפריט "{card}" עודכן מ־8,000,000 ₪ ל־20,000,000 ₪.',
      visual: 'email',
      unlock: { type: 'npc', npc: 'dafna', keywords: ['ביטוח', 'פוליסה', 'כיסוי', 'העלה', 'סכום', 'מיליון'] },
      audience: 'all',
      pointsTo: ['eitan'],
      hint: 'יש שמאית ביטוח באנשי הקשר. תשאלו אותה על הפוליסה.',
      hintFromMin: 50,
    },
    {
      id: 'gal_dm',
      title: 'הודעות שדלפו מ־{chatApp}',
      kind: 'chat',
      summary: 'גל למלווה: "יהיה לי עד שישי. משהו גדול."',
      body: 'שיחה פרטית שדלפה בין gal.flips למשתמש "ש.ק.":\nש.ק.: שבוע שלישי שאתה מאחר.\ngal.flips: יהיה לי עד שישי. משהו גדול.\nש.ק.: כמה גדול?\ngal.flips: גדול מהחוב.',
      visual: 'dm',
      unlock: { type: 'qr', code: 'HUDDLE-7' },
      audience: 'all',
      pointsTo: ['gal'],
      hint: 'מישהו כאן חייב כסף. יש מדבקת QR נוספת בבית.',
      hintFromMin: 75,
    },
    {
      id: 'avner_testimony',
      title: 'עדות: אבנר מיפו',
      kind: 'testimony',
      summary: 'מי ששאל הבוקר על שווי הקלף: צעיר, עם תיק גב, הריח כמו ספריי ניקוי.',
      body: 'אבנר: "ילד. צעיר. עם תיק גב. והריח שלו… כמו ספריי ניקוי של חנות."',
      visual: 'testimony',
      unlock: {
        type: 'npc',
        npc: 'avner',
        keywords: ['נער', 'ילד', 'צעיר', 'בחור', 'תיק', 'מי זה היה', 'איך נראה', 'תאר'],
      },
      audience: 'all',
      pointsTo: ['gal'],
      hint: 'אבנר מיפו יודע מי שאל על הקלף הבוקר. תתעקשו.',
      hintFromMin: 50,
    },
    {
      id: 'eitan_noa_dm',
      title: 'שיחה בין איתן לנועה',
      kind: 'chat',
      summary: 'איתן לנועה: "זה צריך להיראות אמיתי. עד שישי."',
      body: 'eitan.b: זה צריך להיראות אמיתי. עד שישי.\nnoa.grades: לתצוגה בלבד, נכון?\neitan.b: ברור. לתצוגה.',
      visual: 'dm',
      unlock: { type: 'manual' },
      audience: 'all',
      pointsTo: ['eitan', 'noa'],
    },
    {
      id: 'maya_layoffs',
      title: 'מייל פנימי של Hammer & Holo',
      kind: 'email',
      summary: 'בית המכירות על סף קריסה. "בלי המכירה מחר, אין משכורות."',
      body: 'מאת: הנהלה\nאל: צוות\nנושא: מחר\nבלי המכירה מחר, אין משכורות בחודש הבא. תודה שאתם איתנו.',
      visual: 'email',
      unlock: { type: 'time', atMin: 65 },
      audience: 'all',
      pointsTo: ['maya'],
    },
    {
      id: 'kenji_clipping',
      title: 'גזיר עיתון, אוסקה 1998',
      kind: 'document',
      summary: 'כתבה על פריצה לאוסף פרטי באוסקה ב־1998. שום אזכור של הקלף.',
      body: 'גזיר עיתון מתורגם: "פריצה לאוסף של מר מורי. נגנבו כמה פריטים". אין פירוט של הפריטים.',
      visual: 'clipping',
      unlock: { type: 'start' },
      audience: 'all',
      pointsTo: ['kenji'],
    },
  ],

  feed: [
    {
      id: 'p_maya_promo',
      author: 'maya',
      time: '19:30',
      text: 'הערב. רק הערב. {card} בתצוגה פרטית לפני המכירה. 🔨✨',
      image: 'slab-under-spotlight',
      likes: 214,
    },
    {
      id: 'p_eitan_watch',
      author: 'eitan',
      time: '20:02',
      text: 'לילה אחרון שהוא שלי. 🥂',
      image: 'eitan-watch-and-slab',
      likes: 388,
    },
    {
      id: 'p_noa_story',
      author: 'noa',
      time: '20:10',
      text: 'עבודת לילה 🤫 רפליקה לתצוגה בלבד',
      image: 'noa-desk',
      likes: 0,
      deletedClue: 'noa_story',
    },
    {
      id: 'p_rotem_1',
      author: 'rotem',
      time: '20:40',
      text: 'יש אנשים שמוכרים דברים שחצי מהם לא שלהם. סתם אומרת.',
      likes: 57,
    },
    {
      id: 'p_yoni_live',
      author: 'yoni',
      time: '21:05',
      text: '🔴 LIVE עכשיו מהפריוויו! הקלף של אחי לפני שהוא הופך למיליונר',
      image: 'stream-thumbnail',
      likes: 912,
    },
    {
      id: 'p_gal_flip',
      author: 'gal',
      time: '21:12',
      text: 'קניתי ב־40 מכרתי ב־400. ככה עושים את זה 😎',
      likes: 33,
    },
    {
      id: 'p_shira',
      author: 'shira',
      time: '21:20',
      text: 'עוד אולם מאובטח ✅ מצלמות, חיישנים, ושליטה מלאה מהאפליקציה.',
      likes: 18,
    },
    {
      id: 'p_kenji',
      author: 'kenji',
      time: '21:25',
      text: 'אבי היה אומר: קלף לא שוכח מאיפה הוא בא.',
      image: 'old-collection',
      likes: 41,
    },
    {
      id: 'p_rotem_2',
      author: 'rotem',
      time: '21:47',
      text: 'הכל חשוך פה 😂 מישהו יודע מה קרה?',
      likes: 12,
      unlock: { type: 'time', atMin: 33 },
    },
    {
      id: 'p_eitan_after',
      author: 'eitan',
      time: '21:49',
      text: 'הכל בסדר, סתם תקלה. הקלף במקום. 💎',
      likes: 140,
      unlock: { type: 'time', atMin: 34 },
    },
    {
      id: 'p_ido',
      author: 'ido',
      time: '22:15',
      text: 'יש לי משהו שכולם יירצו לראות. DM.',
      likes: 9,
      unlock: { type: 'time', atMin: 60 },
    },
  ],

  stream: {
    channel: 'YoniOpensPacks',
    title: '🔥 PREVIEW NIGHT · הקלף של אחי נמכר מחר ב־20 מיליון',
    vodLength: '2:14:33',
    unlock: { type: 'time', atMin: 55 },
    chat: [
      { t: '21:30', user: 'slabdaddy', text: 'תראה את הקלף!! 😍' },
      { t: '21:34', user: 'tlv_flipper', text: 'כמה זה עולה בכלל' },
      { t: '21:35', user: 'yoni_stan', text: 'יוני תעשה זום!' },
      { t: '21:41', user: 'noctyra_fan', text: 'מי זה עם השעון המטורף' },
      { t: '21:43', user: 'slabdaddy', text: 'האורות כבו?? 😱' },
      { t: '21:43', user: 'tlv_flipper', text: 'תעצרו על 21:43. תסתכלו על היד.', clue: 'stream_frame' },
      { t: '21:44', user: 'shadowmod', text: 'אני רואה אור של ויטרינה' },
      { t: '21:45', user: 'yoni_stan', text: 'חזר!! הכל בסדר?' },
      { t: '21:47', user: 'yoni_stan', text: 'יוני תסתכל אחורה!!!' },
      { t: '21:51', user: 'shadowmod', text: 'יו מי זה בחדר המעילים??', clue: 'coat_room_chat' },
      { t: '21:52', user: 'tlv_flipper', text: 'מישהו עם תיק גב' },
      { t: '21:58', user: 'noctyra_fan', text: 'יוני אתה לא רואה את הצ׳אט בכלל' },
    ],
  },

  dms: [
    {
      id: 'dm_gal_shark',
      title: 'gal.flips ↔ ש.ק.',
      participants: ['gal.flips', 'ש.ק.'],
      clue: 'gal_dm',
      unlock: { type: 'qr', code: 'HUDDLE-7' },
      messages: [
        { from: 'ש.ק.', time: 'יום ג׳ 23:10', text: 'שבוע שלישי שאתה מאחר.' },
        { from: 'gal.flips', time: 'יום ג׳ 23:14', text: 'יהיה לי עד שישי. משהו גדול.' },
        { from: 'ש.ק.', time: 'יום ג׳ 23:15', text: 'כמה גדול?' },
        { from: 'gal.flips', time: 'יום ג׳ 23:21', text: 'גדול מהחוב.' },
      ],
    },
    {
      id: 'dm_eitan_noa',
      title: 'eitan.b ↔ noa.grades',
      participants: ['eitan.b', 'noa.grades'],
      clue: 'eitan_noa_dm',
      unlock: { type: 'manual' },
      messages: [
        { from: 'eitan.b', time: 'לפני שבועיים', text: 'זה צריך להיראות אמיתי. עד שישי.' },
        { from: 'noa.grades', time: 'לפני שבועיים', text: 'לתצוגה בלבד, נכון?' },
        { from: 'eitan.b', time: 'לפני שבועיים', text: 'ברור. לתצוגה.' },
      ],
    },
  ],

  missions: [
    {
      id: 'm_eitan',
      character: 'eitan',
      unlock: { type: 'time', atMin: 70 },
      text: 'גרום לפחות לשני אנשים לחשוד ברותם לפני ההצבעה.',
    },
    {
      id: 'm_noa',
      character: 'noa',
      unlock: { type: 'time', atMin: 70 },
      text: 'אם מישהו שואל על הסטורי מ־20:10, תגידי שזו רפליקה שמאיה הזמינה לתצוגה.',
    },
    {
      id: 'm_yoni',
      character: 'yoni',
      unlock: { type: 'time', atMin: 70 },
      text: 'גרום לשלושה אנשים לעשות משהו מול "המצלמה" שלך. כל אחד שווה 30 צופים.',
    },
    {
      id: 'm_gal',
      character: 'gal',
      unlock: { type: 'time', atMin: 70 },
      text: 'מישהו יחפש את מי שהיה בחדר המעילים. דאג שהחשד ייפול על עידו או על קנג׳י.',
    },
    {
      id: 'm_maya',
      character: 'maya',
      unlock: { type: 'time', atMin: 70 },
      text: 'שכנעי את השולחן שהקלף האמיתי עוד בבניין, ושהמכירה תתקיים.',
    },
    {
      id: 'm_rotem',
      character: 'rotem',
      unlock: { type: 'time', atMin: 70 },
      text: 'מצאי הוכחה שאיתן מסתיר כסף, והציגי אותה לכולם.',
    },
    {
      id: 'm_shira',
      character: 'shira',
      unlock: { type: 'time', atMin: 70 },
      text: 'יש לך את לוג האבטחה. תחליטי מתי לחשוף אותו, ומה זה יעשה לחברה שלך.',
    },
    {
      id: 'm_kenji',
      character: 'kenji',
      unlock: { type: 'time', atMin: 70 },
      text: 'ספר לשלושה אנשים את הסיפור של אביך, וגייס מישהו שיצביע איתך.',
    },
    {
      id: 'm_ido',
      character: 'ido',
      unlock: { type: 'time', atMin: 70 },
      text: 'יש לך את קובץ הסטרים המלא. מכור אותו למי שיציע הכי הרבה, בכסף משחק או בסוד.',
    },
  ],

  beats: [
    {
      id: 'b01_welcome',
      atMin: 0,
      label: 'פתיחה',
      tv: { scene: 'title', title: 'השוד של המאייר', subtitle: 'Hammer & Holo · ערב תצוגה פרטי · 21:00' },
      notify: 'הערב התחיל. פתחו את תיק הדמות שלכם.',
    },
    {
      id: 'b02_maya',
      atMin: 5,
      label: 'מאיה מברכת',
      tv: {
        scene: 'announcement',
        title: 'ברוכים הבאים ל־Hammer & Holo',
        body: 'הערב אתם הראשונים לראות את {card}. מחר בשמונה בערב, הפטיש יורד.',
      },
    },
    {
      id: 'b03_live',
      atMin: 15,
      label: 'יוני בלייב',
      tv: {
        scene: 'stream',
        title: '🔴 LIVE · YoniOpensPacks',
        body: 'יוני משדר את הערב. תגידו שלום למצלמה.',
      },
      notify: 'יוני עלה ללייב. {photoApp} מתעדכן.',
    },
    {
      id: 'b04_blackout',
      atMin: 30,
      label: 'האפלה',
      tv: { scene: 'blackout', seconds: 94, caption: 'הפסקת חשמל' },
      notify: 'החשמל נפל.',
    },
    {
      id: 'b05_calm',
      atMin: 33,
      label: 'רגיעה מדומה',
      tv: { scene: 'announcement', title: 'האורות חזרו', body: 'הקלף במקום. סתם תקלה. נכון?' },
    },
    {
      id: 'b06_uv',
      atMin: 40,
      label: 'בדיקת UV',
      tv: { scene: 'uv', title: 'בדיקת UV', body: 'הכנפיים לא זוהרות. הקלף בוויטרינה מזויף.' },
      release: ['fake_photo', 'uv_test'],
      notify: 'הקלף מזויף. בדקו את הראיות.',
    },
    {
      id: 'b07_hotline',
      atMin: 45,
      label: 'קו החשודים נפתח',
      tv: {
        scene: 'hotline',
        title: 'קו חקירה פתוח',
        body: 'אפשר לדבר עם פקד נילי דגן, עם אבנר מיפו ועם שמאית הביטוח. אנשי קשר באפליקציה.',
      },
      openContacts: ['nili', 'avner', 'dafna'],
      notify: 'פקד נילי דגן פתחה קו חקירה. בדקו את אנשי הקשר.',
    },
    {
      id: 'b08_vod',
      atMin: 55,
      label: 'ההקלטה עולה',
      tv: { scene: 'clue', clue: 'stream_frame' },
      release: ['stream_frame'],
      notify: 'ההקלטה של יוני עלתה ל־{streamApp}.',
    },
    {
      id: 'b09_missions',
      atMin: 70,
      label: 'משימות סודיות',
      notify: 'קיבלתם משימה סודית. רק אתם רואים אותה.',
    },
    {
      id: 'b10_noa_fallback',
      atMin: 95,
      label: 'שחזור סטורי',
      release: ['noa_story'],
      notify: 'מישהו שחזר סטורי שנמחק.',
    },
    {
      id: 'b11_gal_fallback',
      atMin: 100,
      label: 'הודעות דולפות',
      release: ['gal_dm'],
      notify: 'הודעות פרטיות דלפו ל־{chatApp}.',
    },
    {
      id: 'b12_leaks',
      atMin: 110,
      label: 'שני גנבים',
      tv: {
        scene: 'announcement',
        title: 'מערכה שלישית: שני גנבים',
        body: 'הלוג של מערכת האבטחה דלף. ומישהו שלח את השיחה בין איתן לנועה.',
      },
      release: ['security_log', 'eitan_noa_dm', 'insurance_email'],
      notify: 'דליפה גדולה. בדקו את הראיות.',
    },
    {
      id: 'b13_vote',
      atMin: 125,
      label: 'הצבעה',
      tv: {
        scene: 'vote',
        title: 'מי לקח את הקלף?',
        body: 'הצביעו בסוד באפליקציה. אפשר לבחור עד שני חשודים.',
      },
      openVote: true,
      notify: 'ההצבעה נפתחה. מי אחראי?',
    },
    {
      id: 'b14_finale',
      atMin: 140,
      label: 'החשיפה',
      tv: { scene: 'finale', title: 'החשיפה', body: 'שני גנבים. לילה אחד.' },
      finale: true,
      notify: 'החשיפה על המסך.',
    },
  ],

  tools: [
    {
      id: 'slabcert',
      title: 'בדיקת תעודת {grader}',
      prompt: 'הזינו מספר תעודה (8 ספרות)',
      placeholder: '12345678',
      miss: 'לא נמצאה תעודה במספר הזה.',
    },
  ],

  solution: {
    culprits: ['eitan', 'gal'],
    explanation:
      'איתן ביים את הגניבה בשביל כסף הביטוח: הוא העלה את הכיסוי ל־20 מיליון, הזמין מנועה "רפליקה לתצוגה", ' +
      'קיבל משירה גישה לאפליקציית האבטחה והפעיל את ההאפלה ב־21:43. בחושך הוא החליף את הקלפים ושם את האמיתי בז׳קט שלו. ' +
      'אבל גל ראה את ההחלפה על המסך של יוני, ונכנס לחדר המעילים ב־21:51. הקלף האמיתי עדיין כאן, בבית.',
    finaleRiddle: 'הקלף האמיתי לא עזב את הבית. רמז אחרון: {hidingPlace}',
  },

  accusation: { prompt: 'מי אחראי להיעלמות הקלף? אפשר לבחור עד שני חשודים.', maxSuspects: 2 },

  awards: [
    { id: 'detective', title: 'הבלש החד ביותר', description: 'מצא הכי הרבה ראיות.' },
    { id: 'liar', title: 'השקרן הטוב ביותר', description: 'האשם שהכי מעט אנשים חשדו בו.' },
    { id: 'viewers', title: 'מלך הצופים', description: 'יוני: כמה צופים הגעת?' },
    { id: 'paranoid', title: 'חושד בכולם', description: 'מי שהאשים הכי הרבה אנשים.' },
    { id: 'costume', title: 'התחפושת הטובה ביותר', description: 'המארח בוחר.' },
  ],
};
